import { AuthProvider } from "@/providers/auth-provider";
import type { Metadata } from "next";
import { Comfortaa } from "next/font/google";
import "./globals.css";

const font = Comfortaa({ subsets: ["cyrillic", "latin"] });

export const metadata: Metadata = {
  title: "Pro Sebe Store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`dark h-full w-full ${font.className}`}>
      <AuthProvider>
        <body>{children}</body>
      </AuthProvider>
    </html>
  );
}
